language: python
sudo: false

env:
  - LUA="lua 5.2"
  - LUA="lua 5.3"
  - LUA="luajit 2.0"
  - LUA="luajit 2.1"

before_install:
  - pip install hererocks
  - hererocks lua_install --$LUA -r latest
  - source lua_install/bin/activate

install:
  - luarocks install luafilesystem

script:
  - cd test-suite && lua run_tests.lua
